// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/axiangcoding/antonstar-bot/internal/data/table"
)

func newGameNew(db *gorm.DB, opts ...gen.DOOption) gameNew {
	_gameNew := gameNew{}

	_gameNew.gameNewDo.UseDB(db, opts...)
	_gameNew.gameNewDo.UseModel(&table.GameNew{})

	tableName := _gameNew.gameNewDo.TableName()
	_gameNew.ALL = field.NewAsterisk(tableName)
	_gameNew.ID = field.NewUint(tableName, "id")
	_gameNew.CreatedAt = field.NewTime(tableName, "created_at")
	_gameNew.UpdatedAt = field.NewTime(tableName, "updated_at")
	_gameNew.DeletedAt = field.NewField(tableName, "deleted_at")
	_gameNew.Link = field.NewString(tableName, "link")
	_gameNew.PosterUrl = field.NewString(tableName, "poster_url")
	_gameNew.Title = field.NewString(tableName, "title")
	_gameNew.Comment = field.NewString(tableName, "comment")
	_gameNew.DateStr = field.NewString(tableName, "date_str")

	_gameNew.fillFieldMap()

	return _gameNew
}

type gameNew struct {
	gameNewDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Link      field.String
	PosterUrl field.String
	Title     field.String
	Comment   field.String
	DateStr   field.String

	fieldMap map[string]field.Expr
}

func (g gameNew) Table(newTableName string) *gameNew {
	g.gameNewDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gameNew) As(alias string) *gameNew {
	g.gameNewDo.DO = *(g.gameNewDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gameNew) updateTableName(table string) *gameNew {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint(table, "id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")
	g.Link = field.NewString(table, "link")
	g.PosterUrl = field.NewString(table, "poster_url")
	g.Title = field.NewString(table, "title")
	g.Comment = field.NewString(table, "comment")
	g.DateStr = field.NewString(table, "date_str")

	g.fillFieldMap()

	return g
}

func (g *gameNew) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gameNew) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 9)
	g.fieldMap["id"] = g.ID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
	g.fieldMap["link"] = g.Link
	g.fieldMap["poster_url"] = g.PosterUrl
	g.fieldMap["title"] = g.Title
	g.fieldMap["comment"] = g.Comment
	g.fieldMap["date_str"] = g.DateStr
}

func (g gameNew) clone(db *gorm.DB) gameNew {
	g.gameNewDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gameNew) replaceDB(db *gorm.DB) gameNew {
	g.gameNewDo.ReplaceDB(db)
	return g
}

type gameNewDo struct{ gen.DO }

type IGameNewDo interface {
	gen.SubQuery
	Debug() IGameNewDo
	WithContext(ctx context.Context) IGameNewDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGameNewDo
	WriteDB() IGameNewDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGameNewDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGameNewDo
	Not(conds ...gen.Condition) IGameNewDo
	Or(conds ...gen.Condition) IGameNewDo
	Select(conds ...field.Expr) IGameNewDo
	Where(conds ...gen.Condition) IGameNewDo
	Order(conds ...field.Expr) IGameNewDo
	Distinct(cols ...field.Expr) IGameNewDo
	Omit(cols ...field.Expr) IGameNewDo
	Join(table schema.Tabler, on ...field.Expr) IGameNewDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGameNewDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGameNewDo
	Group(cols ...field.Expr) IGameNewDo
	Having(conds ...gen.Condition) IGameNewDo
	Limit(limit int) IGameNewDo
	Offset(offset int) IGameNewDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGameNewDo
	Unscoped() IGameNewDo
	Create(values ...*table.GameNew) error
	CreateInBatches(values []*table.GameNew, batchSize int) error
	Save(values ...*table.GameNew) error
	First() (*table.GameNew, error)
	Take() (*table.GameNew, error)
	Last() (*table.GameNew, error)
	Find() ([]*table.GameNew, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.GameNew, err error)
	FindInBatches(result *[]*table.GameNew, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*table.GameNew) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGameNewDo
	Assign(attrs ...field.AssignExpr) IGameNewDo
	Joins(fields ...field.RelationField) IGameNewDo
	Preload(fields ...field.RelationField) IGameNewDo
	FirstOrInit() (*table.GameNew, error)
	FirstOrCreate() (*table.GameNew, error)
	FindByPage(offset int, limit int) (result []*table.GameNew, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGameNewDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gameNewDo) Debug() IGameNewDo {
	return g.withDO(g.DO.Debug())
}

func (g gameNewDo) WithContext(ctx context.Context) IGameNewDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gameNewDo) ReadDB() IGameNewDo {
	return g.Clauses(dbresolver.Read)
}

func (g gameNewDo) WriteDB() IGameNewDo {
	return g.Clauses(dbresolver.Write)
}

func (g gameNewDo) Session(config *gorm.Session) IGameNewDo {
	return g.withDO(g.DO.Session(config))
}

func (g gameNewDo) Clauses(conds ...clause.Expression) IGameNewDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gameNewDo) Returning(value interface{}, columns ...string) IGameNewDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gameNewDo) Not(conds ...gen.Condition) IGameNewDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gameNewDo) Or(conds ...gen.Condition) IGameNewDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gameNewDo) Select(conds ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gameNewDo) Where(conds ...gen.Condition) IGameNewDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gameNewDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IGameNewDo {
	return g.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (g gameNewDo) Order(conds ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gameNewDo) Distinct(cols ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gameNewDo) Omit(cols ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gameNewDo) Join(table schema.Tabler, on ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gameNewDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gameNewDo) RightJoin(table schema.Tabler, on ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gameNewDo) Group(cols ...field.Expr) IGameNewDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gameNewDo) Having(conds ...gen.Condition) IGameNewDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gameNewDo) Limit(limit int) IGameNewDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gameNewDo) Offset(offset int) IGameNewDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gameNewDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGameNewDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gameNewDo) Unscoped() IGameNewDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gameNewDo) Create(values ...*table.GameNew) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gameNewDo) CreateInBatches(values []*table.GameNew, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gameNewDo) Save(values ...*table.GameNew) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gameNewDo) First() (*table.GameNew, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*table.GameNew), nil
	}
}

func (g gameNewDo) Take() (*table.GameNew, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*table.GameNew), nil
	}
}

func (g gameNewDo) Last() (*table.GameNew, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*table.GameNew), nil
	}
}

func (g gameNewDo) Find() ([]*table.GameNew, error) {
	result, err := g.DO.Find()
	return result.([]*table.GameNew), err
}

func (g gameNewDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.GameNew, err error) {
	buf := make([]*table.GameNew, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gameNewDo) FindInBatches(result *[]*table.GameNew, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gameNewDo) Attrs(attrs ...field.AssignExpr) IGameNewDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gameNewDo) Assign(attrs ...field.AssignExpr) IGameNewDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gameNewDo) Joins(fields ...field.RelationField) IGameNewDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gameNewDo) Preload(fields ...field.RelationField) IGameNewDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gameNewDo) FirstOrInit() (*table.GameNew, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*table.GameNew), nil
	}
}

func (g gameNewDo) FirstOrCreate() (*table.GameNew, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*table.GameNew), nil
	}
}

func (g gameNewDo) FindByPage(offset int, limit int) (result []*table.GameNew, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gameNewDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gameNewDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gameNewDo) Delete(models ...*table.GameNew) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gameNewDo) withDO(do gen.Dao) *gameNewDo {
	g.DO = *do.(*gen.DO)
	return g
}
