export const toolbarMini = ["emoji",
    "headings",
    "bold",
    "italic",
    "strike",
    "link",
    "|",
    "list",
    "ordered-list",
    "check",
    "outdent",
    "indent",
    "|",
    "quote",
    "line",
    "code",
    "inline-code",
    "insert-before",
    "insert-after",
    "|",
    "upload",
    "table",
    "|",
    "undo",
    "redo",
    "|",
    {
        name: "more",
        toolbar: [
            // "both",
            // "code-theme",
            // "content-theme",
            // "export",
            // "outline",
            // "preview",
            // "devtools",
            // "info",
            "help",
        ],
    },]
